name: add mask
on: push
jobs:
  log:
    runs-on: ubuntu-latest
    env: 
      PASSWORD: SecretsPassValue
    steps:
      - run: |
          set-x
          echo "::add-mask::${PASSWORD}"
          echo "${PASSWORD}"
