name: Cache
on: push
jobs:
  cache:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4                         # キャッシュの復元と保存を担う。キャシュは、Githubが管理するキャッシュ保存領域に保存する。
        with:
          key: test-${{ runner.os }}-${{ github.sha }} # ithubが管理するキャッシュ保存領域から完全一致検索するためのキャッシュキー
          path: ${{ github.workspace }}/dummy          # キャッシュ対象のパス。キャッシュするファイルパスであり、リストア先のパスでもある。
          restore-keys: |                              # リストアキー
            test-${{ runner.os }}-
      - run: |
          if [[ -f "${GITHUB_WORKSPACE}/dummy" ]]; then exit 0; fi
          dd if=/dev/urandom of="${GITHUB_WORKSPACE}/dummy" bs=1M count=10
          sleep 30
      - run: ls -lh "${GITHUB_WORKSPACE}/dummy"