name: Go_test
on:
  pull_request:
    paths: ['go/**/*.go']
jobs:
  go-test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: action/checkout@v4
      - name: build-go
        uses: action/setup-go@v5
        with: 
          go-version: '1.22'
      - name: run-test
        run: go test go/excellent/*.go    