name: Missing share data
on: push
jobs:
  share:
    runs-on: ubuntu-latest
    steps:
    - name: source
      id: source
      run: echo "RESULT=hello" >> "${GITHUB_OUTPUT}"     # GITHUB_OUTPUTへの書き込み
    - name: output  
      env:
        OUTPUT: "${{steps.source.outputs.RESULT}}"       # stepsコンテキストから参照 
      run: echo "${OUTPUT}"
